"use client";

import Link from "next/link";
import ReactMarkdown from "react-markdown";
import { Loader2 } from "lucide-react";
import { useGetCurrentPolicyQuery } from "@/features/auth/authApi";
import { PolicyLayout } from "@/components/legal/PolicyLayout/PolicyLayout";
import styles from "@/components/legal/PolicyLayout/PolicyLayout.module.css";

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString(undefined, {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return iso;
  }
}

export function PrivacyPolicy() {
  const { data: policy, isLoading, isError } = useGetCurrentPolicyQuery();

  if (isLoading) {
    return (
      <PolicyLayout title="Privacy Policy" lastUpdated="">
        <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "2rem 0" }}>
          <Loader2 size={20} className="animate-spin" aria-hidden="true" />
          <span>Loading privacy policy...</span>
        </div>
      </PolicyLayout>
    );
  }

  if (policy && !isError) {
    return (
      <PolicyLayout title={policy.title} lastUpdated={formatDate(policy.effective_at)}>
        <ReactMarkdown>{policy.content_md}</ReactMarkdown>
      </PolicyLayout>
    );
  }

  return (
    <PolicyLayout title="Privacy Policy" lastUpdated="March 25, 2026">
      <h2>1. Introduction</h2>
      <p>
        Metrum AI (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;) operates the Infra Agents
        platform, an infrastructure management solution that provides device onboarding, monitoring,
        AI-driven evaluation, and team deployment capabilities. This Privacy Policy explains what
        personal data we collect, how we use it, and the rights you have regarding your data under
        applicable data-protection regulations, including the EU General Data Protection Regulation
        (GDPR).
      </p>

      <h2>2. Data Controller</h2>
      <p>
        Metrum AI acts as the <strong>data controller</strong> for personal data processed through
        the Infra Agents platform. Where a customer organization uses our platform to manage its own
        infrastructure, that organization may also be a data controller and Metrum AI acts as a data
        processor on its behalf. See our Data Processing Agreement for details.
      </p>

      <h2>3. Personal Data We Collect</h2>

      <h3>3.1 Account and Identity Data</h3>
      <ul>
        <li>
          Name, email address, and organization affiliation provided during registration via Auth0
          identity provider.
        </li>
        <li>Role and permission assignments (Platform Admin, Infra Admin, Operator, Viewer).</li>
        <li>
          Authentication tokens and session identifiers managed by Istio service mesh and Auth0.
        </li>
      </ul>

      <h3>3.2 Infrastructure Telemetry Data</h3>
      <ul>
        <li>
          Device identifiers, IP addresses, hostnames, and hardware serial numbers collected during
          device onboarding.
        </li>
        <li>
          Network topology data, rack configurations, and infrastructure relationship mappings.
        </li>
        <li>
          Monitoring metrics including CPU, memory, disk, and network utilization from discovered
          devices.
        </li>
      </ul>

      <h3>3.3 AI and Evaluation Data</h3>
      <ul>
        <li>
          Query traces and evaluation results generated by the KyAI module for AI observability.
        </li>
        <li>Workflow configurations and execution logs from the Operations Manager.</li>
      </ul>

      <h3>3.4 Usage and Audit Data</h3>
      <ul>
        <li>
          API request logs including timestamps, endpoint paths, user identity, and response codes.
        </li>
        <li>RBAC authorization decisions (allow/deny audit trail).</li>
        <li>Browser type, OS version, and IP address of platform users.</li>
      </ul>

      <h2>4. Legal Basis for Processing</h2>
      <p>We process personal data on the following legal bases:</p>
      <ul>
        <li>
          <strong>Contract performance</strong> — To deliver the infrastructure management services
          you have subscribed to.
        </li>
        <li>
          <strong>Legitimate interest</strong> — To maintain platform security, detect anomalies,
          and improve service reliability.
        </li>
        <li>
          <strong>Legal obligation</strong> — To comply with regulatory requirements including audit
          and financial reporting.
        </li>
        <li>
          <strong>Consent</strong> — Where required for optional analytics or marketing
          communications. You may withdraw consent at any time.
        </li>
      </ul>

      <h2>5. How We Use Your Data</h2>
      <ul>
        <li>Authenticate users and enforce role-based access control.</li>
        <li>Discover, onboard, and monitor infrastructure devices on your behalf.</li>
        <li>Generate AI evaluations, topology maps, and operational insights.</li>
        <li>Produce audit trails for security compliance and incident response.</li>
        <li>Improve platform performance, reliability, and user experience.</li>
      </ul>

      <h2>6. Data Sharing and Third Parties</h2>
      <p>
        We do not sell personal data. Data may be shared with the following categories of
        recipients:
      </p>
      <ul>
        <li>
          <strong>Identity providers</strong> — Auth0 for authentication and session management.
        </li>
        <li>
          <strong>Cloud infrastructure</strong> — Kubernetes cluster operators and storage backends
          (PostgreSQL, Redis, MinIO, Vault) deployed within your environment or ours.
        </li>
        <li>
          <strong>Sub-processors</strong> — Any third-party vendors are listed in our Data
          Processing Agreement and are bound by equivalent data-protection obligations.
        </li>
      </ul>

      <div className={styles.callout}>
        <p>
          All inter-service communication is encrypted with mutual TLS via Istio service mesh. Data
          at rest in PostgreSQL and MinIO is encrypted using AES-256.
        </p>
      </div>

      <h2>7. International Data Transfers</h2>
      <p>
        If personal data is transferred outside the European Economic Area (EEA), we ensure
        appropriate safeguards are in place, including Standard Contractual Clauses (SCCs) approved
        by the European Commission, or reliance on an adequacy decision.
      </p>

      <h2>8. Data Retention</h2>
      <p>
        We retain personal data only for as long as necessary to fulfil the purposes described in
        this policy. Specific retention periods are detailed in our{" "}
        <Link href="/data-retention-policy">Data Retention Policy</Link>.
      </p>

      <h2>9. Your Rights</h2>
      <p>Under the GDPR, you have the following rights regarding your personal data:</p>
      <ul>
        <li>
          <strong>Access</strong> — Request a copy of the personal data we hold about you.
        </li>
        <li>
          <strong>Rectification</strong> — Request correction of inaccurate or incomplete data.
        </li>
        <li>
          <strong>Erasure</strong> — Request deletion of your personal data where there is no
          compelling reason for continued processing.
        </li>
        <li>
          <strong>Restriction</strong> — Request restriction of processing in certain circumstances.
        </li>
        <li>
          <strong>Data portability</strong> — Receive your data in a structured, machine-readable
          format.
        </li>
        <li>
          <strong>Objection</strong> — Object to processing based on legitimate interests.
        </li>
        <li>
          <strong>Withdraw consent</strong> — Where processing is based on consent, withdraw it at
          any time.
        </li>
      </ul>
      <p>
        To exercise any of these rights, contact us at{" "}
        <a href="mailto:privacy@metrum.ai">privacy@metrum.ai</a>. We will respond within 30 days.
      </p>

      <h2>10. Security Measures</h2>
      <ul>
        <li>Mutual TLS (mTLS) between all microservices via Istio.</li>
        <li>JWT-based authentication with Istio ingress validation.</li>
        <li>PyCasbin RBAC enforcement with default-deny policy across all API endpoints.</li>
        <li>Encrypted secrets management via HashiCorp Vault.</li>
        <li>Audit logging of all authorization decisions with structured log output.</li>
      </ul>

      <h2>11. Cookies and Tracking</h2>
      <p>
        The Infra Agents platform uses only essential cookies required for authentication session
        management. We do not use third-party advertising or analytics cookies. Session tokens are
        stored securely and expire according to your organization&apos;s configured session policy.
      </p>

      <h2>12. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy to reflect changes in our practices or legal requirements.
        Material changes will be communicated through the platform and via email to account
        administrators. Continued use of the platform after updates constitutes acceptance of the
        revised policy.
      </p>

      <h2>13. Contact</h2>
      <p>
        If you have questions or concerns about this Privacy Policy, contact our Data Protection
        Officer:
      </p>
      <ul>
        <li>
          Email: <a href="mailto:privacy@metrum.ai">privacy@metrum.ai</a>
        </li>
        <li>Address: Metrum AI, Data Protection Office</li>
      </ul>
      <p>
        You also have the right to lodge a complaint with your local data protection supervisory
        authority.
      </p>
    </PolicyLayout>
  );
}

export default PrivacyPolicy;
